CREATE TABLE IF NOT EXISTS USERS 
    (user_id INTEGER PRIMARY KEY NOT NULL,
    username TEXT,
    timezone TEXT,
    reg_date TEXT);

CREATE TABLE IF NOT EXISTS ROUTES
    (route_id INTEGER PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL,
    url TEXT NOT NULL UNIQUE,
    name TEXT,
    is_active INTEGER NOT NULL DEFAULT 1);
